version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:8000"
    environment:
      - .env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./secrets.txt:/app/secrets.txt

volumes:
  static_volume:
  media_volume: