version: '3.8'
services:
  web:
    image: zubair275/hrmanage:latest 
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=46.51.134.19,localhost,127.0.0.1