version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    secrets:
      - django_secret_key
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=46.51.134.19,localhost,127.0.0.1
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

secrets:
  django_secret_key:
    external: true

volumes:
  static_volume:
  media_volume: