version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:8000"
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=3.251.65.76,localhost,127.0.0.1
      - DJANGO_SECRET_KEY=)-q*gw@^c7)%0-_c84(5wl@8ecek%n$4yx_u%02p8ro5&os+^7
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./secrets.txt:/app/secrets.txt


volumes:
  static_volume:
  media_volume:
