version: '3.8'

services:
  web:
    image: hrmanage:latest
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=False
      - ALLOWED_HOSTS=46.51.134.19,localhost,127.0.0.1
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
    restart: unless-stopped

volumes:
  static_volume: